version: '3'

services:
  app:
    container_name: sample_cs_app
    build:
      dockerfile: ./docker/localhost/app/Dockerfile
      context: .
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
      - 5102:5102
      - 7055:7055
      - 14713:14713
    volumes:
      - .:/app
    tty: true
    depends_on:
      - mysql

  mysql:
    container_name: sample_cs_mysql
    build:
      dockerfile: ./docker/localhost/mysql/Dockerfile
      context: .
    ports:
      - 3306:3306
    volumes:
      - ./docker/localhost/mysql/sql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "user", "-ppassword"]
     timeout: 20s
     retries: 10

